on:
  label:
    types:
      - created
  issues:  
    types: [opened, labeled]       
  push:    
    branches: main
      - main
    tags:
      - V2
      - V1.*    
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:    
     - run: echo "hello world"  
